- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
Since I have not been able to reproduce the bug, this is a potential fix that need to be tested out in production by brand. Since crash happend due to 
"Failed to parse date ["Oct 31, 2021 21:37:46"]: Invalid number: Oct"
dates are now stored as a number (10 for oct).
> 1755 Bugfix gson date format

- webflows/src/main/java/com/schibsted/account/webflows/client/RetrofitClient.kt
- webflows/src/test/java/com/schibsted/account/webflows/client/RetrofitClientTest.kt
By request from developers. 
Check in order to know if they can use retrofitclient, or if resumeLastLoggedInUser is needed to be called before they can make authenticated requests.
> Is initialized fun for retrofitclient

- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/main/java/com/schibsted/account/webflows/persistence/compat/LegacySessionStorage.kt
- webflows/src/main/java/com/schibsted/account/webflows/persistence/compat/MigratingSessionStorage.kt
- Solution in order to make it possible to migrate from old SPID sdk where tokens are not stored in same shared preference file as old sdk
> Enable to forward filename to where legacy tokens are stored

- webflows/src/main/java/com/schibsted/account/webflows/persistence/compat/LegacySessionStorage.kt
- webflows/src/test/java/com/schibsted/account/webflows/persistence/compat/LegacySessionStorageTest.kt
- In order to allow developers of SDK to use Proguard -keepattributes *Annotation* for migration flow
> Remove @SerializedName from tokens in LegacySession

- webflows/build.gradle
There seems to be a bug throwing InvalidProtocolBufferException in unique cases for later versions. This is an attempt to remove this crash
> Decreasing androidx.security:security-crypto:1.1.0-alpha03 to alpha01

- webflows/src/main/java/com/schibsted/account/webflows/token/IdTokenValidator.kt
- webflows/src/test/java/com/schibsted/account/webflows/token/IdTokenValidatorTest.kt
For PRE we are requesting ACR: `eid-se` or `eid-no` to be able to differentiate different eid methods for Norway and Sweden. But resulted AMR is simply `eid` to keep it consistent with Production. This PR aims to fix IDTokenValidator to expect `AMR=eid` if requested ACR value is `eid-se` or eid-no`
> AMR for Eid will only contain eid without prefix

- app/build.gradle
- webflows/consumer-rules.pro
**Why this change**
Users will experience errors from the SDK in form of Proguard obfuscations not finding proper classes. This PR is an attempt to make users not have to add SDK related Proguard config in their own Proguard rules file.
**What was changed**
Proguard rules was updated to keep some classes. It was put in the consumer-rules.pro because it's up to the app module (third party that uses this SDK) to enable Proguard and then these rules will automatically apply.
> feature/81 Add proguard rules to keep classes and not throw errors

- webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
**Why this change**
The shared preferences can crash if the data is corrupted. A change was necessary to make the shared preferences mutable and support being rebuilt, not only on instantiation but also dynamically when storing/retrieving values.
**What was changed**
The shared preferences is now mutable and support being purged and created anew.
> feature/143 Change shared preference to be mutable and support being rebuilt

- webflows/src/main/AndroidManifest.xml
- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthorizationManagementActivity.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
**Why this change**
Received error reports of crashes happening on resuming of AuthorizationManagementActivity
**What was changed**
Added fallback to regular browser if Custom Tabs are not supported
> Fallback to regular browser if Custom Tabs are not supported.

- app/src/main/java/com/schibsted/account/example/ManualLoginActivity.kt
- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthResultLiveData.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/ClientInterface.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/RetrofitClient.kt
- webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
- webflows/src/main/java/com/schibsted/account/webflows/persistence/StorageError.kt
- webflows/src/main/java/com/schibsted/account/webflows/persistence/compat/MigratingSessionStorage.kt
- webflows/src/test/java/com/schibsted/account/webflows/activities/AuthResultLiveDataTest.kt
- webflows/src/test/java/com/schibsted/account/webflows/client/ClientTest.kt
- webflows/src/test/java/com/schibsted/account/webflows/client/RetrofitClientTest.kt
- webflows/src/test/java/com/schibsted/account/webflows/persistence/compat/MigratingSessionStorageTest.kt
- webflows/src/test/java/com/schibsted/account/webflows/user/UserTest.kt
Handle possible exceptions in EncryptedSharedPrefsStorage:
Log the error and in case of read operation, propagate the error to the
caller (to be able to signal problem resuming user session).
> Revert logout on storage failure

- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/test/java/com/schibsted/account/webflows/client/ClientTest.kt
Cloudflare returns either 502 or 504 with an HTML page when we have server outages. This PR fixes the crash that occurs when we have outages
> Don't attempt to parse error objects from 5xx responses

- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthorizationManagementActivity.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
If the `AuthorizationManagementActivity` is killed, the login flow would be continuously restarted as the `savedInstanceState` was not used when the activity resumed (hence ignoring the value of `authStarted`).
1. Update device settings: In "Developer Options", enable "Don't keep activities"
2. Start the example app.
3. Start the login flow and complete it.
4. Verify you end up back in the app as successfully logged-in.
> Fix resume of authorization management activity

- README.md
- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthResultLiveData.kt
- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthorizationManagementActivity.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/RetrofitClient.kt
- webflows/src/test/java/com/schibsted/account/webflows/client/RetrofitClientTest.kt
To support users logging in, not being resumed from existing storage.
1. Create a  `RetrofitClient` instance.
1. Test the "automatic" flow
1. Pass the `RetrofitClient` to `AuthorizationManagementActivity.setup` (for example in `ExampleApp.kt`
1. Verify the automatic resume of User via AuthResultLiveData works, and that `RetrofitClient.makeAuthenticatedRequest` works.
1. Verify fresh login works: Trigger the login flow, and then switch user in the web flow to login as a different user. A new call to `RetrofitClient.makeAuthenticatedRequest` uses the tokens of the recently logged-in user.
> Fix RetrofitClient: update reference to user on every new login.

- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthResultLiveData.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
If user cancels login flow (from eiD) we should return `NotAuthed.CancelledByUser` so that it can be handled separately by the mobile apps.
This will allow mobile apps to handle this case the same way as if user canceled login flow by closing the custom tabs.
> Throw different error type if user cancels login

- app/src/main/java/com/schibsted/account/example/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/LoginPromptContentProvider.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/LoginPromptFragment.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/LoginPromptManager.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/SessionInfoDatabase.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/SessionInfoManager.kt
clean main activity
Run requestLoginPrompt in background thread
> call loginPrompt from Client

- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthResultLiveData.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
Complementary PR for https://github.com/schibsted/account-sdk-android-web/pull/83 but to branch started from 5.0.0 tag
* Throw different error type if user cancels login
* Check error before state
- throw NotAuthed.CancelledByUser error
* Fix typo
Fix for 5.0.0 version
> 5.0.1 - Throw different error type if user cancels login (#83)

- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/LoginPromptFragment.kt
- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/LoginPromptManager.kt
```
FATAL EXCEPTION: main
Process: com.schibsted.account, PID: 18798
kotlin.UninitializedPropertyAccessException: lateinit property loginPromptConfig has not been initialized
```
Repro steps:
-Turn on “Don’t keep activities” (Dev options of device)
-Open app, request prompt
-Minimize app
-Open app
This is adressed by 27ff9230a7dc59371e859e04d54a14c01e11b465
I've also spotted one more although I can not reporduce it. Stacktrace was pointing on situation where we were trying to add another prompt with the same tag. f6585d7539f68091b51c98e7da8ac854bd366fed should prevent such problems
> Login prompt crash

- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
When we correctly check that there is no session in storage -> on Success with null result is returned.
> Correctly check session persence

- webflows/src/main/java/com/schibsted/account/webflows/loginPrompt/LoginPromptFragment.kt
That should be batter probalbly
> Remove login promp on login click

- webflows/consumer-rules.pro
One of Klarta devs reported issue that when he was using minify the SDK was unstable and it throwed such error:
```
else if (superclass == TypeToken.class) {
throw new IllegalStateException("TypeToken must be created with a type argument: new TypeToken<...>() {}; "
+ "When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.");
}
```
The problem starts in:
```
schibstedAccountApi.getJwks { ... }
```
Is located in: 
```
com.nimbusds.jose.shaded.gson.reflect.TypeToken 
```
which is used during parsing:
```
com.nimbusds.jose.util.JSONObjectUtils.parse(...)
```
and results in such info:
```
Token error response: IdTokenNotValid(cause=UnexpectedError(message=Failed to fetch JWKS to validate ID Token))
```
The solution is pretty simple - lets keep classes …
> feat: NOJIRA Fix consumer-rules to keep com.nimbusds.jose JWK classes

- app/src/main/java/com/schibsted/account/example/MainActivity.kt
- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthResultLiveData.kt
- webflows/src/main/java/com/schibsted/account/webflows/activities/AuthorizationManagementActivity.kt
- webflows/src/test/java/com/schibsted/account/webflows/activities/AuthResultLiveDataTest.kt
- webflows/src/test/java/com/schibsted/account/webflows/activities/AuthorizationManagementActivityTest.kt
- webflows/src/test/java/com/schibsted/account/webflows/user/UserTest.kt
Fix lateinit property by saving the client settings passed during `setup`
Added some test to backup that solution is working
> fix: UUI-814 fix crash for lateinit instance property

- webflows/consumer-rules.pro
https://schibsted.ghe.com/app-foundation/android-hermes-app/issues/8326
As I've established this error
```
Token request error response: UnexpectedError(cause=com.google.gson.JsonIOException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.schibsted.account.webflows.api.UserTokenResponse)
```
Was caused by R8 stripping out UserTokenResponse constructor (as it's used by GSON only with reflection) and made GSON think this is an abstract class.
A simple fix is to explicitly tell R8 that constructors of all API classes should not be removed.
Before | After |
|--------|-------|
|   ![image](https://github.com/user-attachments/assets/c56a0c83-4e18-4344-a17c-81cec0ba6b71)     | …
> Keep class constructor

- webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
- webflows/src/main/java/com/schibsted/account/webflows/client/ClientConfiguration.kt
Added a new `skipLegacySessionMigration` flag to `ClientConfiguration` to allow apps to opt out of migrating sessions from EncryptedSharedPrefsStorage.
When enabled, the SDK skips reading from the legacy keystore-backed storage, avoiding potential ANRs caused by blocking operations on the main thread— especially on Android 12 devices with slow or hardware-backed keystores.
Default behavior remains unchanged to preserve backward compatibility.
> feat(storage): allow disabling legacy session migration from EncryptedSharedPreferences
